### PR TITLE
AIMS-107, AIMS-108, AIMS-109, AIMS-110 Add item detail page

### PR DESCRIPTION
**Pull request by rfox2**
**What**: Added a first pass at an item detail page that will show current item information including status, the history of what has happened with the object at the Annex, and how often an item was requested and shipped/scanned.

**How**

* Added a new controller method and route
* Added a new query class for activity logs with item_history and item_usage methods
* Created the item detail page
* Added some i18n for activity messages
* Created appropriate unit tests

### CODE REVIEW

**Comment by rfox2** [comment]
Will address hound issues tomorrow

**Comment by jgondron** [comment]
:+1:

**Comment by jaronkk** [comment]
I'd like to start under the assumption that we'll use a gin index on data.  To take advantage of that we'll need to use different operators.  For now I'd like to change the where data->item->>barcode to the following: `where("data @> ?", { item: { barcode: item.barcode } }.to_json)`.  Here's a description of the jsonb operators: http://www.postgresql.org/docs/9.4/static/functions-json.html#FUNCTIONS-JSONB-OP-TABLE

I would also like to avoid repetition where possible, so doing something like:

```ruby
module ActivityLogQuery
  module_function

  def for_item(item)
    relation.where("data @> ?", { item: { barcode: item.barcode } }.to_json)
  end

  def item_history(item)
    for_item(item).
      where(action: ['StockedItem','UnstockedItem','CreatedItem','DestroyedItem']).
      order(action_timestamp: :desc)
  end
```

**Comment by jaronkk** [comment]
:+1:

**Pull request merged**
