### PR TITLE
Aims tray types

### PR DESCRIPTION
**Pull request by afstanton**
This encompasses several tickets regarding tray types. I'd like a first pass review on the code, please. Likely needs some UI tweaking before going to production.

### CODE REVIEW

**Comment by rfox2** [comment]
image

**Comment by rfox2** [comment]
image

**Comment by rfox2** [comment]
Might want to normalize the heading values on the text at the top as well so that it's consistent

**Comment by afstanton** [comment]
Thanks for the feedback, I'll work on it!

**Pull request merged**
