### PR TITLE
AIMS-321: Batch items filter

### PR DESCRIPTION
**Pull request by jgondron**
Why: User would like to additionally be able to filter the items that match a request.
How: Each sub table will now use DataTables. I also had to modify the way that the global request filters work since these are applied to all datatables, not just specific instances.

### CODE REVIEW

**Comment by rfox2** [comment]
:+1:

**Comment by jaronkk** [comment]
@rfox2 Can you re-review this with the new changes?

**Comment by jaronkk** [comment]
:+1: For @jgondron's  stuff, and he already :+1:ed https://github.com/ndlib/annex-ims/pull/118

**Comment by rfox2** [comment]
:+1:

**Pull request merged**
